FROM php:8.0-apache

# Install zip
RUN apt-get update && apt-get install -y libzip-dev

# Install PDO and mysql connector
RUN docker-php-ext-install pdo pdo_mysql mysqli zip && docker-php-ext-enable mysqli

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

# Copy php dependenies installer script
COPY install-dependencies.sh ./
