services:
  php-apache:
    container_name: php-apache
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ../php/:/var/www/html/php/:ro,z
    ports:
      - 8000:80
    depends_on:
      - database
      - mailserver

  database:
    container_name: database
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: Climbers_Soul_Caiarosio
      MYSQL_USER: user123
      MYSQL_PASSWORD: password123
    volumes:
      - ../sql/:/docker-entrypoint-initdb.d/:ro,z
    ports:
      - 9906:3306

  mailserver:
    container_name: mailserver
    image: marlonb/mailcrab:v1.3.0
    ports:
      - 1025:1025 # smtp server
      - 1080:1080 # web ui

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: database
    ports:
      - 8080:80
    depends_on:
      - database
